<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks>net11.0</TargetFrameworks>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="11.0.0-preview.6.26359.118" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Sharingan.Extensions.DependencyInjection\Sharingan.Extensions.DependencyInjection.csproj" />
    </ItemGroup>

</Project>